services:
  - type: web
    name: aplus
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
