services:
  # A Docker web service
  - type: web
    name: aplus-website
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RUST_LOG
        value: info
      - key: APP_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MAILTRAP_API_KEY
        sync: false # ðŸ‘ˆ runtime environment variable
